version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"

    open-pull-requests-limit: 5

    groups:
      python-dependencies:
        patterns:
          - "*"

    commit-message:
      prefix: "deps"
